"""empty message

Revision ID: 4dc2817f1b23
Revises: b1149be92d4b
Create Date: 2021-04-22 12:39:02.830256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc2817f1b23'
down_revision = 'b1149be92d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transports', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
