"""empty message

Revision ID: b1149be92d4b
Revises: 
Create Date: 2021-04-22 12:21:33.466786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1149be92d4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_type', sa.String(length=128), nullable=False),
    sa.Column('rent_fee', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transports')
    # ### end Alembic commands ###
